name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: rust-llvm

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-containers:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            os: "ubuntu-latest",
            version: "linux"
          }
          - {
            os: "windows-2022",
            version: "win"
          }
    permissions:
      packages: write
      contents: read
    outputs:
      tag: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        id: set-tag
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_OUTPUT
          TAG=$IMAGE_ID:$VERSION
          echo "TAG=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT

      - name: Build image
        working-directory: ${{ matrix.config.version }}
        shell: bash
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        if: ${{ github.event_name != 'pull_request'}} # && matrix.config.version == 'linux'}}
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        shell: bash
        if: ${{ github.event_name != 'pull_request'}} # && matrix.config.version == 'linux'}}
        run: |
          TAG=${{ steps.set-tag.outputs.TAG }}-${{ matrix.os.version }}
          docker tag $IMAGE_NAME $TAG
          docker push $TAG

  publish-containers:
    name: Publish docker images
    runs-on: ubuntu-latest
    needs: build-containers
    if: ${{ github.event_name != 'pull_request'}} # && matrix.config.version == 'linux'}}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        if: ${{ github.event_name != 'pull_request'}} # && matrix.config.version == 'linux'}}
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Manifest
        run: |
          docker manifest create ${{ needs.build-containers.outputs.tag }} \
           --amend ${{ needs.build-containers.outputs.tag }}-linux \
           --amend ${{ needs.build-containers.outputs.tag }}-win \
        - name: Docker push
          run: |
            docker manifest push ${{ needs.build-containers.outputs.tag }}


      
